sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t irusio/fibonnaci -f Dockerfile .

script:
  - docker images
  - docker run -e CI=true irusio/fibbonacci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibbonacci-test"
  env: "fibbonaccitest-env"
  bucket_name: "elasticbeanstalk-us-east-1-092118888492"
  bucket_path: "fibbonacci"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY